# Generated by Django 2.1.5 on 2019-03-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0003_auto_20190323_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='status',
            field=models.CharField(choices=[('o', 'open'), ('c', 'closed')], max_length=1, null=True),
        ),
    ]
